Repository WildCodeSchool/2022-09-php-orleans-project-gatinaisnature, pull requests merged in 2022-10, with the labels that each got.

#24 Initialization
  public/assets/css/style.css
  src/View/layout.html.twig
Labels: Reviewed, Corrections Done

#48 Fix fonts
  public/assets/css/style.css
  src/View/layout.html.twig
Labels: Reviewed

#44 S01 US07 evenements mis à jour dans cette request (sans les activités…
  database.sql
  public/assets/images/imgPlaceHolder.jpg
  src/Controller/ActivityController.php
  src/Model/EventManager.php
  src/View/Activity/activity.html.twig
  src/routes.php
Labels: Reviewed

#34 S01 us06 activity page creation
  database.sql
  public/assets/css/activity.css
  src/Controller/ActivityController.php
  src/Model/ActivityManager.php
  src/View/Activity/activity.html.twig
  src/routing.php
Labels: Reviewed, conflicts resolved

#55 please accept this merge of dev into main
  database.sql
  public/assets/css/activity.css
  public/assets/images/imgPlaceHolder.jpg
  src/Controller/ActivityController.php
  src/Model/ActivityManager.php
  src/Model/EventManager.php
  src/View/Activity/activity.html.twig
  src/routes.php
  src/routing.php
Labels: Reviewed

#46 Navbar
  public/assets/css/style.css
  public/assets/images/favicon.png
  src/View/Home/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Corrections Done

#49 S01 us04
  public/assets/css/activity.css
  public/assets/css/index.css
  public/assets/images/asso-presentation.png
  public/assets/images/imgPlaceHolder.jpg
  public/assets/images/president.png
  public/assets/images/secretaire.png
  public/assets/images/tresorier.png
  src/View/Home/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Corrections Done

#32 S01US02 : Mettre en forme le footer
  public/assets/css/footer.css
  public/assets/css/style.css
  src/View/Activity/activity.html.twig
  src/View/Home/index.html.twig
  src/View/Include/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Corrections Done

#58 Fix activity folder
  public/assets/css/activity.css
  public/assets/images/imgPlaceHolder.jpg
  src/View/Activity/activity.html.twig
Labels: conflicts resolved
