Repository WildCodeSchool/2022-09-php-orleans-project-gatinaisnature, pull requests merged in 2022-11, with the labels that each got.

#56 S01 us03
  public/assets/css/index.css
  public/assets/images/home-bird.jpg
  public/assets/images/home-forest.jpg
  src/View/Home/index.html.twig
  src/View/Include/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#95 Fix dev#1
  src/View/Home/index.html.twig
  src/View/Include/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Fix

#51 S01 us08
  database.sql
  public/assets/css/circuits.css
  public/assets/css/style.css
  public/assets/images/fall-g02112eec4_1280_11zon.jpg
  src/Controller/CircuitController.php
  src/Model/CircuitManager.php
  src/View/Circuits/chooseCircuits.html.twig
  src/routes.php
Labels: Reviewed, Corrections Done

#80 Fix navbar
  public/assets/css/header.css
  src/View/Include/_header.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Fix, conflicts resolved

#79 S02 us14
  database.sql
  public/assets/css/form.css
  src/Controller/ContactController.php
  src/View/Contact/form.html.twig
  src/routes.php
Labels: Reviewed, Corrections Done

#98 Fix root#2
  public/assets/css/circuits.css
  public/assets/css/header.css
  public/assets/css/style.css
  src/View/Activity/activity.html.twig
  src/View/Circuits/chooseCircuits.html.twig
  src/View/Components/_footer.html.twig
  src/View/Components/_header.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#100 Dev to Main
  database.sql
  public/assets/css/circuits.css
  public/assets/css/form.css
  public/assets/css/header.css
  public/assets/css/index.css
  public/assets/css/style.css
  public/assets/images/fall-g02112eec4_1280_11zon.jpg
  public/assets/images/home-bird.jpg
  public/assets/images/home-forest.jpg
  public/assets/images/purty-wood.png
  src/Controller/CircuitController.php
  src/Controller/ContactController.php
  src/Model/CircuitManager.php
  src/View/Activity/activity.html.twig
  src/View/Circuits/chooseCircuits.html.twig
  src/View/Components/_footer.html.twig
  src/View/Components/_header.html.twig
  src/View/Contact/form.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed

#102 S02 fix activity picture link
  database.sql
  public/assets/upload/.gitignore
  src/Controller/ActivityController.php
  src/Model/ActivityManager.php
  src/View/Activity/activity.html.twig
  src/View/Activity/add.html.twig
  src/View/layoutAdmin.html.twig
  src/routes.php
Labels: Reviewed

#87 change of the activity side to alternate the image and text
  public/assets/css/activity.css
  src/Controller/ActivityController.php
  src/View/Activity/activity.html.twig
Labels: Reviewed, Conflicts

#101 S02 us12
  database.sql
  public/assets/images/lest.jpg
  src/Controller/LandscapeController.php
  src/View/Landscape/landscape.html.twig
  src/routes.php
Labels: Reviewed

#112 picture instead of picture_link
  src/View/Activity/activity.html.twig
Labels: Reviewed

#111 first commit for the fix to put again the files who disappeared
  src/Controller/ActivityController.php
  src/Model/ActivityManager.php
  src/View/Activity/add.html.twig
  src/routes.php
Labels: Reviewed, Corrections Done

#114 modif root font size header toggle form of title for every page
  public/assets/css/header.css
  public/assets/css/style.css
  src/View/Components/_header.html.twig
  src/View/Contact/form.html.twig
Labels: Reviewed, Fix

#115 footerFix clean et replace
  public/assets/css/footer.css
  src/View/Components/_footer.html.twig
Labels: Reviewed, Fix, Corrections Done

#118 modif img place
  database.sql
  src/View/Circuits/show.html.twig
Labels: Reviewed, Fix

#116 Fix activity dev
  public/assets/css/activity.css
  src/View/Activity/activity.html.twig
Labels: Reviewed, Corrections Done

#107 S02 us20 créer table especes
  database.sql
  public/assets/css/form.css
  public/assets/css/species.css
  src/Controller/OrganismController.php
  src/Model/OrganismManager.php
  src/View/Organism/index.html.twig
  src/routes.php
Labels: Reviewed, Corrections Done

#109 S02 us16
  composer.lock
  database.sql
  src/Controller/CircuitController.php
  src/Model/CircuitManager.php
  src/View/Circuits/chooseCircuits.html.twig
  src/View/Circuits/circuits-add.html.twig
  src/routes.php
Labels: Reviewed, Corrections Done

#123 S02US27_delete_activity
  src/Controller/ActivityController.php
  src/View/Activity/index.html.twig
  src/routes.php
Labels: Reviewed, Corrections Done

#125 S02 us17
  public/assets/css/circuit-index.css
  src/Controller/CircuitController.php
  src/View/Circuits/indexAdmin.html.twig
  src/routes.php
Labels: Reviewed

#120 S02US28_fonction_edit_sans_show
  src/Controller/ActivityController.php
  src/Model/ActivityManager.php
  src/View/Activity/edit.html.twig
  src/View/Activity/index.html.twig
  src/routes.php
Labels: Reviewed

#124 S03US38 make a carousel for species and landscapes
  public/assets/css/circuit-page.css
  public/assets/js/carousel.js
  src/View/Circuits/show.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#133 S02 US18 : edit circuits
  database.sql
  src/Controller/CircuitController.php
  src/Model/CircuitManager.php
  src/View/Circuits/edit.html.twig
  src/View/Circuits/show.html.twig
  src/routes.php
Labels: Reviewed

#135 add routes to navbar Admin
  src/View/Components/_headerAdmin.html.twig
  src/routes.php
Labels: Reviewed, Fix

#136 first commit ajouter evenement
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Event/add.html.twig
  src/routes.php
Labels: Reviewed

#134 S02 US19 : delete circuits
  src/Controller/CircuitController.php
  src/View/Circuits/indexAdmin.html.twig
  src/routes.php
Labels: Reviewed

#137 S03 us15 créer interface admin
  database.sql
  public/index.php
  src/Controller/LoginController.php
  src/Model/UserManager.php
  src/View/Admin/login.html.twig
  src/View/Components/_footer.html.twig
  src/View/Errors/error.html.twig
  src/routes.php
Labels: Reviewed

#132 S03 us21 add organism
  public/assets/css/organism.css
  src/Controller/OrganismController.php
  src/Model/OrganismManager.php
  src/View/Organism/add.html.twig
  src/View/Organism/index.html.twig
  src/routes.php
Labels: Reviewed

#129 S03US30_lister_evenements
  public/assets/css/event-index.css
  src/Controller/EventController.php
  src/View/Event/index.html.twig
  src/routes.php
Labels: Reviewed

#139 S03US32 first delete evenements first commit
  src/Controller/EventController.php
  src/routes.php
Labels: Reviewed

#141 S03US34_lister_paysages
  public/assets/css/landscape-index.css
  src/Controller/LandscapeController.php
  src/Model/LandscapeManager.php
  src/View/Landscape/indexAdmin.html.twig
  src/routes.php
Labels: Reviewed, conflicts resolved

#143 SO3US33_ajout_paysage_first_commit
  src/Controller/LandscapeController.php
  src/Model/LandscapeManager.php
  src/View/Landscape/add.html.twig
  src/View/Landscape/indexAdmin.html.twig
  src/routes.php
Labels: Reviewed

#140 S03 US15 add logout and index admin
  public/assets/images/corbakeu.jpg
  src/Controller/AdminController.php
  src/Controller/LoginController.php
  src/View/Admin/index.html.twig
  src/View/Components/_headerAdmin.html.twig
  src/View/Errors/error.html.twig
  src/routes.php
Labels: Reviewed, Corrections Done

#146 Fix home responsive
  public/assets/css/index.css
  public/assets/images/asso-presentation.png
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#144 fix pour changer la balise <a> par un <btn> pour la fonction supprime…
  src/View/Event/index.html.twig
Labels: Reviewed

#147 FixJqueryLink replace cdn out of script balise
  src/View/Circuits/show.html.twig
  src/View/layout.html.twig
  src/View/layoutAdmin.html.twig
Labels: Reviewed, Fix

#150 S03 us35 edit paysage
  src/Controller/LandscapeController.php
  src/Model/LandscapeManager.php
  src/View/Landscape/edit.html.twig
  src/View/Landscape/indexAdmin.html.twig
  src/routes.php
  src/routing.php
Labels: Reviewed

#153 S03US36_supprimer_paysage
  src/Controller/LandscapeController.php
  src/routes.php
Labels: Reviewed

#154 Fix Index Admin Circuits : ajout de liens vers les pages du CRUD
  src/View/Circuits/indexAdmin.html.twig
Labels: Reviewed, Fix

#157 S03FIX_correction_nom_root_admin_index_evenements
  src/routes.php
Labels: Reviewed

#158 fixPlaceHolder replace null on img database
  database.sql
  src/View/Circuits/chooseCircuits.html.twig
  src/View/Circuits/show.html.twig
Labels: Reviewed, Fix

#160 S03FIX_modif_nom_lien_picture_BDD
  database.sql
  src/Model/EventManager.php
Labels: Reviewed

#163 Fix Uploads : renommage du dossier Upload en "Uploads"
  public/assets/uploads/.gitignore
  src/Controller/ActivityController.php
  src/Controller/CircuitController.php
  src/Controller/EventController.php
  src/Controller/LandscapeController.php
Labels: Reviewed, Fix

#165 S04FIX_taille_carateres_non_requise_text_description
  src/Controller/ActivityController.php
  src/Controller/EventController.php
Labels: Reviewed

#170 Fix add switch link admin visitor
  src/View/Components/_header.html.twig
  src/View/Components/_headerAdmin.html.twig
Labels: Reviewed, Fix

#171 Rework of form contact
  public/assets/css/form.css
  src/View/Contact/form.html.twig
Labels: Reviewed, Fix

#167 Fix Legal : lien vers site de mentions légales
  src/View/Components/_footer.html.twig
Labels: Reviewed, Fix

#174 Fix landscape page
  public/assets/css/landscape-index.css
  src/Controller/LandscapeController.php
  src/View/Landscape/landscape.html.twig
Labels: Reviewed, Fix

#173 Fix responsive error html twig
  public/assets/css/error.css
  src/View/Errors/error.html.twig
Labels: Reviewed, Fix

#175 Fix Displaying Carrousel : affichage des espèces et paysages dans le carroussel
  src/Controller/CircuitController.php
  src/Model/CircuitManager.php
  src/View/Circuits/circuits-add.html.twig
  src/View/Circuits/edit.html.twig
Labels: Reviewed, Fix

#176 Fix replace h2 class on h2
  src/View/Activity/activity.html.twig
  src/View/Circuits/chooseCircuits.html.twig
  src/View/Circuits/show.html.twig
  src/View/Contact/form.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#172 Fix resize title nav for mobile
  public/assets/css/style.css
  src/View/Components/_header.html.twig
Labels: Reviewed, Fix, Corrections Done, conflicts resolved

#168 S04FIX_format_date_evenements
  src/Model/EventManager.php
  src/View/Activity/activity.html.twig
Labels: Reviewed, Fix

#181 changement lien activité image "picture au lien de picture_link pour matcher avec la BDD"
  src/View/Activity/activity.html.twig
Labels: Reviewed, Fix

#179 Fix LOGIN change design of connection page
  public/assets/css/login.css
  src/View/Admin/login.html.twig
  src/View/Contact/form.html.twig
Labels: Reviewed, Fix

#185 Fix add anim to pic of circuit
  public/assets/css/circuits.css
Labels: Reviewed, Fix

#196 Fix Circuit Decimal : validation d'une saisie numérique pour la longueur du circuit
  src/Controller/CircuitController.php
Labels: Reviewed, Fix

#197 mise à jour lien sur controllers et views
  public/uploads/.gitignore
  src/Controller/ActivityController.php
  src/Controller/CircuitController.php
  src/Controller/EventController.php
  src/Controller/LandscapeController.php
  src/View/Activity/activity.html.twig
  src/View/Activity/edit.html.twig
  src/View/Circuits/circuits.html.twig
  src/View/Circuits/edit.html.twig
  src/View/Circuits/show.html.twig
  src/View/Event/edit.html.twig
  src/View/Landscape/edit.html.twig
  src/View/Landscape/landscape.html.twig
Labels: Reviewed, Fix

#200 Add modal delete
  src/View/_modalDelete.html.twig
Labels: Reviewed, Fix

#202 Fix design event admin
  public/assets/css/event-index.css
  src/View/Event/add.html.twig
  src/View/Event/edit.html.twig
  src/View/Event/index.html.twig
  src/View/formAdminEvent.html.twig
Labels: Reviewed, Fix

#203 Fix design circuit admin
  public/assets/css/circuit-index.css
  src/View/Circuits/add.html.twig
  src/View/Circuits/edit.html.twig
  src/View/Circuits/index.html.twig
  src/View/formAdminCircuit.html.twig
Labels: Reviewed, Fix

#204 Fix design landscape admin
  public/assets/css/landscape-index.css
  src/View/Landscape/add.html.twig
  src/View/Landscape/edit.html.twig
  src/View/Landscape/indexAdmin.html.twig
  src/View/formAdminLand.html.twig
Labels: Reviewed, Fix

#207 Fix modif btn carrousel empty
  src/View/Circuits/show.html.twig
Labels: Reviewed, Fix

#209 Fix modif img size to be good in tablet
  public/assets/css/index.css
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#210 Fix security breach
  src/Controller/AbstractController.php
  src/Controller/ActivityController.php
  src/Controller/AdminController.php
  src/Controller/CircuitController.php
  src/Controller/EventController.php
  src/Controller/LandscapeController.php
  src/Controller/LoginController.php
  src/Controller/OrganismController.php
  src/routes.php
Labels: Reviewed, Fix

#211 Fix Change Alt : changement d'un "Alt" d'une image
  src/View/Circuits/show.html.twig
Labels: Reviewed, Fix

#212 Fix delete submit
  src/View/_modalDelete.html.twig
Labels: Reviewed, Fix

#214 Fix / on delete
  src/View/Landscape/indexAdmin.html.twig
Labels: Reviewed, Fix

#217 Fix btn edit
  src/View/Activity/add.html.twig
  src/View/Activity/edit.html.twig
  src/View/Circuits/add.html.twig
  src/View/Circuits/edit.html.twig
  src/View/Event/add.html.twig
  src/View/Event/edit.html.twig
  src/View/Landscape/add.html.twig
  src/View/Landscape/edit.html.twig
  src/View/Organism/add.html.twig
  src/View/Organism/edit.html.twig
  src/View/formAdminActivity.html.twig
  src/View/formAdminCircuit.html.twig
  src/View/formAdminEvent.html.twig
  src/View/formAdminLand.html.twig
  src/View/formAdminOrga.html.twig
Labels: Reviewed, Fix

#216 Fix Header Location : correction des redirections pour CRUD circuit
  src/Controller/CircuitController.php
Labels: Reviewed, Fix

#215 Fix hidden Id
  src/View/formAdminActivity.html.twig
  src/View/formAdminCircuit.html.twig
  src/View/formAdminEvent.html.twig
  src/View/formAdminLand.html.twig
  src/View/formAdminOrga.html.twig
Labels: Reviewed, Fix

#218 Fix vh-100 clean
  src/View/Organism/index.html.twig
Labels: Reviewed, Fix

#206 Fix Form Features : correction de divers problèmes liés aux forms
  database.sql
  src/Controller/CircuitController.php
  src/Model/CircuitManager.php
  src/View/Circuits/add.html.twig
  src/View/Contact/form.html.twig
  src/View/formAdminCircuit.html.twig
Labels: Reviewed, Fix

#219 dev to main
  database.sql
  public/assets/css/activity-index.css
  public/assets/css/activity.css
  public/assets/css/circuit-index.css
  public/assets/css/event-index.css
  public/assets/css/index.css
  public/assets/css/landscape-index.css
  public/assets/css/organism.css
  public/uploads/.gitignore
  src/Controller/AbstractController.php
  src/Controller/ActivityController.php
  src/Controller/AdminController.php
  src/Controller/CircuitController.php
  src/Controller/EventController.php
  src/Controller/LandscapeController.php
  src/Controller/LoginController.php
  src/Controller/OrganismController.php
  src/Model/CircuitManager.php
  src/View/Activity/activity.html.twig
  src/View/Activity/add.html.twig
  src/View/Activity/edit.html.twig
  src/View/Activity/index.html.twig
  src/View/Circuits/add.html.twig
  src/View/Circuits/circuits.html.twig
  src/View/Circuits/edit.html.twig
  src/View/Circuits/index.html.twig
  src/View/Circuits/show.html.twig
  src/View/Components/_footer.html.twig
  src/View/Components/_headerAdmin.html.twig
  src/View/Contact/form.html.twig
  src/View/Event/add.html.twig
  src/View/Event/edit.html.twig
  src/View/Event/index.html.twig
  src/View/Home/index.html.twig
  src/View/Landscape/add.html.twig
  src/View/Landscape/edit.html.twig
  src/View/Landscape/indexAdmin.html.twig
  src/View/Landscape/landscape.html.twig
  src/View/Organism/add.html.twig
  src/View/Organism/edit.html.twig
  src/View/Organism/index.html.twig
  src/View/_modalDelete.html.twig
  src/View/formAdminActivity.html.twig
  src/View/formAdminCircuit.html.twig
  src/View/formAdminEdit.html.twig
  src/View/formAdminEvent.html.twig
  src/View/formAdminLand.html.twig
  src/View/formAdminOrga.html.twig
  src/routes.php
Labels: Reviewed

#220 Fix favicon
  public/assets/images/favicons/android-chrome-192x192.png
  public/assets/images/favicons/apple-touch-icon.png
  public/assets/images/favicons/favicon-16x16.png
  public/assets/images/favicons/favicon-32x32.png
  public/assets/images/favicons/favicon.ico
  src/Controller/CircuitController.php
  src/Controller/LandscapeController.php
  src/Model/CircuitManager.php
  src/View/Circuits/show.html.twig
  src/View/Landscape/landscape.html.twig
  src/View/layout.html.twig
  src/View/layoutAdmin.html.twig
  src/routes.php
Labels: Fix

#222 Fix add link paysages
  database.sql
  src/Controller/CircuitController.php
  src/Model/CircuitManager.php
  src/View/Circuits/add.html.twig
  src/View/Contact/form.html.twig
  src/View/formAdminCircuit.html.twig
Labels: Fix

#223 Dev to Main
  public/assets/css/circuits.css
  public/assets/images/favicons/android-chrome-192x192.png
  public/assets/images/favicons/apple-touch-icon.png
  public/assets/images/favicons/favicon-16x16.png
  public/assets/images/favicons/favicon-32x32.png
  public/assets/images/favicons/favicon.ico
  src/Controller/CircuitController.php
  src/Controller/LandscapeController.php
  src/Model/CircuitManager.php
  src/View/Circuits/show.html.twig
  src/View/Landscape/landscape.html.twig
  src/View/layout.html.twig
  src/View/layoutAdmin.html.twig
  src/routes.php
Labels: Reviewed
